# Generated by Django 5.2.4 on 2025-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_field',
            field=models.DateField(default='date'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_time_field',
            field=models.DateTimeField(default='date time'),
        ),
        migrations.AddField(
            model_name='student',
            name='email_field',
            field=models.EmailField(default='email please', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='text_field',
            field=models.TextField(default='type please'),
        ),
    ]
