# Generated by Django 5.2.4 on 2025-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_date_field_student_date_time_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_field',
        ),
        migrations.AddField(
            model_name='student',
            name='time_field',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_time_field',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
