# Generated by Django 5.2.4 on 2025-08-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_remove_student_date_field_student_time_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_time_field',
        ),
    ]
