# Generated by Django 5.2.4 on 2025-08-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_remove_student_date_time_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_field',
        ),
        migrations.RemoveField(
            model_name='student',
            name='text_field',
        ),
        migrations.RemoveField(
            model_name='student',
            name='time_field',
        ),
    ]
