# Generated by Django 5.2.4 on 2025-08-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_remove_student_email_field_remove_student_text_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='text_field',
            field=models.TextField(default='type please'),
        ),
    ]
