# Generated by Django 5.2.4 on 2025-08-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_student_text_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='text_field',
        ),
    ]
